### ISSUE TITLE
Dockerhub: latest tag

### ISSUE THREAD

**Issue by strarsis** [kfatehi/docker-sinopia#22]
Why is the latest tag so much smaller in Dockerhub compared to all the other tags, 
even the tag with highest version number - improved build?

**Comment by roytruelove** [comment]
+1

**Comment by juanpicado** [comment]
If you haven't seen the deprecation noticed #30 yet, anyhow, `verdaccio` use tags already https://hub.docker.com/r/verdaccio/verdaccio/tags/
