### ISSUE TITLE
@-scoped packages not handled

### ISSUE THREAD

**Issue by jmellor** [kfatehi/docker-sinopia#27]
I can install and publish scoped packages to a Sinopia registry but can't install scoped packages from an upstream repository (e.g. http://registry.npmjs.com/).

e.g: npm install package '@kadira/storybook'

gives a 404 error when the repository is Sinopia, but works just fine from registry.npmjs.com
Sinopia doesn't seem to handle URLs with @ scoping correctly.

**Comment by kfatehi** [comment]
Sinopia has not been updated since 2015 -- I looked at the open PR's and discovered https://github.com/rlidwka/sinopia/pull/448/files -- the suggested alternative is https://github.com/verdaccio/verdaccio

**Comment by jmellor** [comment]
Thanks!  I have fired up a test Verdaccio Docker image, and am encouraged by what I see.  I can easily sell this to Dev as it looks and feels like Sinopia.

One question though: I want to seamlessly move one night from Sinopia to Verdaccio, but I cannot see a means of manually copying all the NPMs from one to the other.  Pulling and pushing them seems like a poor transfer mechanism, as I need to identify which ones are local and which are cached from upstream.  Is there a better way of doing it, like copying a directory and the Sinopia objects just appearing in Verdaccio or something similar?

**Comment by kfatehi** [comment]
Try asking in an issue under the veraccio project.
